# scale-deployment-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shubham-scale-deployments
  namespace: dev
subjects:
  - kind: User
    name: shubham
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: scale-deployments
  apiGroup: rbac.authorization.k8s.io
