apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ui
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-ui
  template:
    metadata:
      labels:
        app: static-ui
    spec:
      containers:
      - name: nginx
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-ui
  namespace: dev
spec:
  type: NodePort
  selector:
    app: static-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
